### ISSUE TITLE
Object size, zoom and clipping (units and documentation)

### ISSUE THREAD

**Issue by gnbl** [jscad/OpenJSCAD.org#167]
An object with length 800 (I would like to use millimeters, so 800 mm = 80 cm = 0.8 m, about 31") is clipped at about half that once zoomed out to full extent:

```
function main() {
   return cube({size: [400,800,28], center: true});
}
```

What are the limits to the object size? 

On a related note: [the documentation](https://en.wikibooks.org/wiki/OpenJSCAD_User_Guide) does not seem to include anything about real-world units.

**Comment by z3dev** [comment]
@gnbl Thanks for the interest in OpenJSCAD.org

The size of the plate, as well as well as the position of the camera can be be changed. But we don't have an example.

There really aren't any limits on the size of an object, however the object is scaled to the screen fit.

The plate can show the real size of the objects, but the size of the plate needs to be configured to reflect the real size. For example, the plate can be configured to show minor grids every 10 units, instead of 1 unit. Or the size can be configured to 3000 units. The default size is 200  units, with minor grids every 1 unit, and major grids every 10 units.

Finally, there isn't a fixed "unit" of measure. The objects are built based on strict math, so the unit can be anything, e.g. 1 mm, 1 inch, 1 yard, 1 mile. However, 3D printing (The focus of OpenJSCAD.org) is based on millimeters, so most people consider one unit to mean one millimeter.

So, it's really up to you. You can create large objects but the camera and the plate need to be configured correctly. Or you can "scale" those large objects to fit within the current settings. I also suggest that the "real unit" of measure is also specified on the website.

Hope that helps

**Comment by z3dev** [comment]
Thanks.

The image shows the view of the camera. In this case, the camera is moved out to scale to the object. But there's a configured limit, so there's "clipping".

You have two options...
- Scale the objects to fit the rendering, i.e. obj.scale(0.1)
- gProcessor.viewer.setCameraOptions(...)

I found a bug in the setting of the options, so I think the first option is probably the best.

**Comment by z3dev** [comment]
@gnbl Release 0.5.2 corrected some issues with the Processor options. Please use the lates release.

In addition, there's a new example. Please see big.html for how to set the parameters.

Please let us know if there are any further issues or questions.

**Comment by kaosat-dev** [comment]
I will be adding adaptative (infinite?) clipping in a future version of the viewer

**Comment by knickers** [comment]
It seems that `gProcessor` is not available as a variable inside my script, and I can't seem to find how to call the `setCameraOptions` function. Is there anyone who could explain this?

**Comment by WolfgangFahl** [comment]
Can't we get an answer for Version 1.9.0?

**Comment by gnbl** [comment]
I can confirm that the behavior (clipping) is still present in the current 1.9.0.

My link from above (supposed to load the script from pastebin at http://pastebin.com/raw/ddSKNNpC) results in an error:

> 
> Error: The JSCAD script must contain a function main() which returns one or more CSG or CAG solids.
> Line: 89,col: 0
> (blob:https://openjscad.org/cb164d66-a1a5-49c1-a6e1-828e9b9eba2c line 43 > Function)

and the code window contains:

> // Invalid file type in conversion ()

I might open an issue on that later, if someone hasn't already.

This is the script, if someone wants to test directly:
```
function main() {
   return cube({size: [400,800,1], center: true}).translate([0,0,-1]);
}

// [SHIFT+RETURN to update model]
// zoom out all the way
// enjoy clipping
```

Thanks for your work!

**Comment by WolfgangFahl** [comment]
z3dev wrote:

> The size of the plate, as well as well as the position of the camera can be be changed. But we don't have an example.

It would be great to get such an example. I'd like to increase the plate size to 220 x 220

**Comment by z3dev** [comment]
There’s an example on how to create a version of OpenJSCAD that changes the options for the viewer. It’s called ‘opts’.

The distribution bundled (dist/opts.js) via bundled together based on the code found in src/ui/opts.js

https://github.com/jscad/OpenJSCAD.org/blob/master/packages/web/src/ui/opt.js

You cannot changed these parameters interactively, so a new bundle will have to be created.

**Comment by WolfgangFahl** [comment]
@z3dev 
I do not know what todo from the comment above. I don't know how to create a bundle and do not know where bundle creation is described/documented.

**Comment by WolfgangFahl** [comment]
Still can't figure out how to do this for version 1.9.0 but need it.

**Comment by WolfgangFahl** [comment]
How would i know what to do now? Please provide an example.

**Comment by hrgdavor** [comment]
Your script would be like this in jscad v2

```js
const jscad = require('@jscad/modeling')
const { cuboid } = jscad.primitives


function main() {
   return cuboid({size: [400,800,28]});
}

module.exports = { main }

```

_cube from v1 is now cuboid, and builtin objects are cenetered by default._

 - open https://openjscad.xyz/
 - check 'Enable Auto-zoom"
 - Save that script into a file
 - drag and drop the file onto the openjscad window

The model will be loaded, and jscad will zoom out to display the whole model

![image](https://user-images.githubusercontent.com/2480762/117501403-e8668780-af75-11eb-85ba-58d183fd1f23.png)
