### ISSUE TITLE
General features

### ISSUE THREAD

**Issue by berserk82** [jscad/OpenJSCAD.org#257]
Hello again. I wonder if this project does support the following features:
undo
redo
cut
copy
paste
save/export
new
close
open
zoom

Thanks in advance for either.

Bye, Ivano.

**Comment by kaosat-dev** [comment]
Hello again !
Did know you actually use OpenJSCAD directly ? https://openjscad.org/ 
I really encourage you to do so, because it would answer most of your questions.
Are you aware that OpenJSCAD is a **text/code** based 2D/3Dmodelling program ?
So :
- undo redo : yes , in a way, undo redo of the **text** you typed
- cut copy : same
- new : yes
- open / close : no , and does not make sense given how OpenJScad works
- save/export:  yes, multiple formats in 2d & 3d
- zoom : yes  ,the 3d view : also rotate & pan

**Comment by berserk82** [comment]
Thanks. Sorry, but I can't access my computer for a while and that's why I asked.

**Comment by kaosat-dev** [comment]
@berserk82 ok, sorry about that :)
