### ISSUE TITLE
MouseClick on parameters moves 3D View

### ISSUE THREAD

**Issue by gilboonet** [jscad/OpenJSCAD.org#281]
I'm adding parameters to a script and when I click on the parameter panel to change a value, it moves the 3D View. It also does the same when I click on the Code panel.. version 0.5.2 didn't have this bahaviour.

**Comment by z3dev** [comment]
@gilboonet thanks

I found the same while testing but your explanation is much better.

**Comment by kaosat-dev** [comment]
@gilboonet this issue is also present when moving /dragging the mouse inside the code editor:) (the new behaviour is my bad the old camera controls where full of hacks, so I changed quite a bit: ) 
one easy fix is to have the camera controls ONLY rotate/pan etc when your mouse is in the 3D VIEW and nowhere else (which makes the most sense to me imho)

**Comment by hawkerm** [comment]
Yeah, I'm clicking in the code editor to edit my code and its rotating my 3d view, it's very confusing and distracting.  It's making the tool unusable for me. :(

**Comment by z3dev** [comment]
Definitely a major issue.

@kaosat-dev do you have a quick solution? If not then I will fix this weekend.

**Comment by gilboonet** [comment]
v 1.4.0 closes this
