### ISSUE TITLE
difference with an array of 3d objects causes error

### ISSUE THREAD

**Issue by borrillis** [jscad/OpenJSCAD.org#359]
## Expected Behavior
no errors

## Actual Behavior
TypeError: a[i].setColor is not a function

## Steps to Reproduce the Problem

  1. open OpenJSCAD.org in borwser
  2. copy in the following code:
function main() {  
   var cubes = new Array();
   for(i=0; i<20; i++) {
      cubes[i] = rotate([0,i/20*360,0], 
         translate([i,0,0], 
         rotate([0,i/20*90,i/20*90,0], 
         cube({size:[1,1.2,.5],center:true}))));
   }
   return difference(
      cube({size:[30,30,0.1],center:true}),
      translate([3,0,0],cube()),
      difference(
         rotate([0,-45,0], cube({size:[8,7,3],center:true})),
         sphere({r:3,fn:20,center:true})
      ),
      translate([10,5,5], scale([0.5,1,2], sphere({r:5,fn:50}))),
      translate([-15,0,0], cylinder({r1:2,r2:0,h:10,fn:20})),
      cubes
   );
}
  3. Hit F5

## Specifications

  - Version:
  - Platform:
  - Environment: (browser, local server, node.js etc)

**Comment by z3dev** [comment]
@borrillis Thanks. I’ll check this out.

I’d like to ask one thing. Are you sure that the final set of objects is complete, i.e. there are no null or undefined objects?

**Comment by borrillis** [comment]
I'm fairly certain. 

If I Union the cubes array first, everything works fine, it seems that it's only failing if an array of CSG objects is passed in.

Also if I limit the array to 2 elements and hardcode each element into the difference() it works. e.g. difference(cube({size:[30,30,0.1],center:true}), holes[0], holes[1]).

**Comment by z3dev** [comment]
@borrillis Very interesting indeed...

difference() allows two different styles...
- list of arguments, where each is a single object, e.g. difference(obj1,obj2,obj3,obj4,...)
- an array of objects, e.g. difference(**[obj1,obj2,obj3,obj4,...]**)

BUT doesn't handle a combination of single objects and arrays, i.e. difference(obj1,[obj2,obj3,obj4],obj5,...)

That's the issue here. The arguements are a mixed. The one causing the trouble is 'cubes', which is an array.

I suggest using the 'cubes' array to hold all those pieces. Arrays are simple structures, which can be manipulated easily.
- array.push(obj) to add an object

I'll let you figure out how to make the code change. It shouldn't be difficult.
