### ISSUE TITLE
jscad desktop - infinite loop issues with require

### ISSUE THREAD

**Issue by hedefalk** [jscad/OpenJSCAD.org#385]
As discussed on https://plus.google.com/116532201566282200688/posts/djurtJxUb4j

Here is my repo where the issue occurs. (the repo is just work in progress porting an openscad thing)
https://gitlab.com/hedefalk/eurorack-jscad/edit

Drag the _links_ folder into the desktop app.

Depending on if I use this line or the one following the error is toggled on/off:
https://gitlab.com/hedefalk/eurorack-jscad/blob/master/eurorack-lib/eurorack-lib.js#L39

The only difference is where the calculation is put.

I tried reproducing in a standalone thing but it didn't seem to be trivial…

ping @kaosat-dev

**Comment by kaosat-dev** [comment]
Hi again @hedefalk !
Thanks for the bug report, I will take a look at what is going on.

**Comment by kaosat-dev** [comment]
Ok found the answer :)
your `mountSurfaceHeight2` has a value of `nan`since it is computed based on a `railHeight` from constants , but you do not export it :)

**Comment by kaosat-dev** [comment]
hmm there seems to be something else too

**Comment by kaosat-dev** [comment]
so the infinite loop error is when you pass a `NaN` value to translate() 
This will be fixed in the V2.0 of the API (which will be quite different).
Also thanks for the bug report this made me realise:
* dev console needs to be toggle able to inspect values of variables (I had to throw errors with the values to be able to see them)
* there are too many useless dependencies in the `vtree` module (vtree/ geometry caching will very likely be part of the future v2 core, so this is good to see now)

**Comment by hedefalk** [comment]
Awesome thanks! Silly me, need to turn on some linting I guess, I thought I had :)

>dev console needs to be toggle able to inspect values of variables (I had to throw errors with the values to be able to see them)

Yeah, dev console would be awesome!

I'll close this one, thanks a lot for looking into it!

**Comment by kaosat-dev** [comment]
no problem @hedefalk glad I could help ! :)
