### ISSUE TITLE
Rotation with mouse button

### ISSUE THREAD

**Issue by runsun** [jscad/OpenJSCAD.org#39]
I am left-handed mouse user, so the mouse buttons are switched. (btw, consider using "main/secondary" in replace of "left/mouse" to describe the mouse buttons).

The instruction says that [Right mouse] for xy rotation and [Left mouse] for xz. In my case, it is the [Left mouse] button (the physical right button) controls rotations of all directions, and the [Right mouse] button (the physical left button) has no function at all. 

Don't know if this is just me. I am using Linux Mint running Chrome. It'd be great if the 2nd button (the [Right mouse]) is set for panning like OpenCad does. In the current setting, the panning is set to either [Middle mouse](which doesn't work in my case, either 'cos it's the wheel in the middle and pushing in resulting in zooming) or Shift-[Left mouse], which works but needs both hands.

**Comment by thehans** [comment]
I submitted a patch that fixes right click dragging, so that Rotate XY works now.  

I tested out the new rotation in the viewer for the first time (the alternative gesture of "Alt + Left click" is used to drag application windows on my Linux box, so it is unusable for rotation), and while it looks neat, it seems like something that would be used much less frequently than panning, if at all.

Also I have a touchpad on my laptop in which middle click + dragging emulates scrollwheel, so middle clicks drags are not possible to use for panning.
 Shift + Left Mouse is the only panning option I can use, which is two handed as runsun mentioned.  I think switching Right Mouse to panning would be an improvement.

**Comment by z3dev** [comment]
The standard mouse event has an indication of which button was pressed. This should standard should be followed. Also, the help should be changed as well to say 'main' and 'secondary' buttons.

https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button

A number representing a given button:

    0: Main button pressed, usually the left button or the un-initialized state
    1: Auxiliary button pressed, usually the wheel button or themiddle button (if present)
    2: Secondary button pressed, usually the right button
    3: Fourth button, typically the Browser Back button
    4: Fifth button, typically the Browser Forward button

For a mouse configured for left-handed use, the button actions are reversed. In this case, the values are read from right to left.

**Comment by z3dev** [comment]
@runsun Can you try the current version of V1 JSCAD at www.openjscad.org ? I believe this has been fixed.

If so then please close.

**Comment by z3dev** [comment]
@runsun Can you try the new version of V2 JSCAD at www.jscad.xyz ? I believe this issue has been fixed.
