### ISSUE TITLE
Proposal: bring all code from JScad repostitories into this one

### ISSUE THREAD

**Issue by kaosat-dev** [jscad/OpenJSCAD.org#426]
# The issue:
More and more people are trying to contribute to Jscad, but the multiple repositories setup is making that considerably harder than it needs to be. 
The split to different repositories was needed when originally trying to make the large code base manageable, but now we can have the advantages of multiple smaller modules with a single repo thanks to Monorepos/ Lerna.

# Proposal  ?
The idea is this
- we bring at least `@jscad/io` into the current repository
- the files would be at package/io/ and keep their current structure, so something like    
    * packages/io/stl-serializer
    * packages/io/svg-deserializer
    * etc
- this means: 
   * a single monorep
   * a single command to set up a development environement
   * less issues and complexity 
- not too sure about Csg.js , perhaps we can see to that after V2

**Comment by BarbourSmith** [comment]
As someone who is trying to get an understanding of how the code is distributed this makes a lot of sense to me. I found the multi-repo system to be confusing when I was first trying to figure out where files were. That being said I still don't have a complete understanding of all the interconnects so there may be reasons for having multiple repos that I don't know about.

**Comment by hg42** [comment]
I also found confusing that the main component (csg) is in it's own repo, while web, cli, desktop are together.
So, I already move csg.js into package/csg by cloning it as a sub-repo, because then it's managed automatically by lerna.
Unfortunately when changing a branch in OpenJSCAD.org it was removed again.

I am still in the steep learning phase according to all these node tools. I also only got a glance on git sub-modules.

However, wouldn't it be possible to have the packages in packages/* as git sub-modules while managing the packages with lerna?
I hope, this would combine all advantages.
Someone using only a basic package (mainly csg) could do this without bothering with the whole jscad ecosystem, while others could clone jscad as a whole, because the sub-modules can be pulled by the base system. Adding more packages should be made easy, may be like a plugin system, so that users could also add such packages. I don't know if lerna handles sub-folders. This would be useful to organize all the packages, e.g. user plugins could go to a separate folder and cli, web, desktop could be moved to "frontends" or similar.

**Comment by kaosat-dev** [comment]
@BarbourSmith Even I can relate :)
The reason for multiple repos is both that some code was originally maintained by different people in different repos, and some of our own decisions when starting to upgrade jscad. These days a single one would be better imho.

@hg42 sorry for the pains, but we are learning from the mistakes :) 
About git sub modules: I would rather avoid that to be honest, I had a ton of issues in the past when coupled with other package managers (npm/lerna etc), I even had an early prototype of the various jscad repos using git submodules and it was a pain to deal with.
About the various 'plugins' etc as you say , what we hope for V2 is really just providing both 
- reusable specialised 'bricks' (core/renderer/geometry tooling) like the Stack.gl (gl-vec2& 3 etc) 
- wrapper ui/tools (WEB, CLI, desktop) for convenience that play well with tools & designs from various different sources

A lot of people do a lot of great tools, functions etc, so we would like everybody's work to be useable the same way as our bricks.
In another domain, the 'callbags' project (https://github.com/staltz/callbag-basics) has a nice phylosophy and ecosystem of a simple 'spec' that people can build against, and a lot of user created modules.

**Comment by kaosat-dev** [comment]
@z3dev what is your opinion on this ? :)

**Comment by gilboonet** [comment]
Years ago, I had been able to modify jscad code in order to tweak it the way I wanted to integrate it with my web site, I was then able to add a new 2D output format (gcode) and add functions to load/save parameters from a script, and some others minors changes to the UI. But now it is too complex for me and I didn't manage to integrate into web version the off output format that I added to jscad/io. So, for newbie github developers like me it would be handful to have a single repository or to have some documentation to understand how to integrate new code in the multi repository system that seems something really powerful.

**Comment by kaosat-dev** [comment]
@gilboonet thanks for the feedback, your feedback & difficulties with off format etc are one of the reasons for this proposal.
We will still have lots of specialized packages like in IO, but all inside this repository, so you would not have that many 'moving parts' and repos to deal with.
Also agreed about documentation. That is our greatest weakness I think, and is a must have for V2.
stay tuned ! :)

**Comment by BarbourSmith** [comment]
@gilboonet I am interested in the ability to export gcode also if you would like to collaborate

**Comment by gilboonet** [comment]
@BarbourSmith What I did was quite straigthforward. I reused the svg output into a call to a function called svg2gcode from a github project called gcode simulator. As it was using three.js, I needed to include 7 js to index.html, and as I'm using a laser cutter without Z axis I tweaked svg2Gcode to remove this, and that's it. It's targeted to version 0.5.0 of jscad and I didn't use github at this moment. Now with node there is certainly an easier way to do the same directly from a cag.
You can see it here : http://gilboo.carton.free.fr/OJSC5/
![Uploading Capture d’écran de 2019-02-11 10-35-34.png…]()

**Comment by MaslowCreate** [comment]
That is fantastic! I will do the same thing. Thanks for the tip!

**Comment by z3dev** [comment]
Done in V2
