### ISSUE TITLE
Naming Objects

### ISSUE THREAD

**Issue by thesourcerer8** [jscad/OpenJSCAD.org#558]
I would like to be able to assign (programmatically) names to objects and have those names be used when exporting to X3D, STL, ... where the export formats support names, so that I can more easily reference the objects in X3D.
Support for the animation capabilities of X3D would be great as well.

I have been asked to reassign this issue here:
https://github.com/EinsteinsWorkshop/BlocksCAD/issues/17#issuecomment-308742189

**Comment by z3dev** [comment]
@thesourcerer8 can you help define what you would like the X3D file to contain? there's a lot of possibilities.

https://www.web3d.org/x3d/content/examples/X3dSceneAuthoringHints.html#NamingConventions

**Comment by thesourcerer8** [comment]
Yes, a DEF attribute seems to be the way to do it.

**Comment by z3dev** [comment]
Do you want names in another export format, like DXF?

**Comment by thesourcerer8** [comment]
I think it would be a good idea to put the names in all the output formats that support them.

**Comment by z3dev** [comment]
Support of 'name' attribute added to V2 DXF serializer. #684

**Comment by z3dev** [comment]
Comment... each serializer should provide a list of supported attributes, such as 'name' or 'class' or 'id'. In addition, these attributes need to be preserved by generalize(), possible a new option.

**Comment by z3dev** [comment]
From the forum...

'class' element for sure is interesting as it will ease styling. About 'id', yes it must be used carefully to ensure that each object has its unique id, generally I use names forged from data (line between triangle 23 and 111 has id 'L_23_111', etc.). 'name' is deprecated so it's maybe wise to avoid it, on very old js code I remember i used 'tag', as svg doesn't use it, as svg can use custom attributes, it can be anything. And it would be really great to have exported svg from jscad with such fine details, because it will allow rework those outputs with great ease.

**Comment by z3dev** [comment]
Support of 'id' and ‘class’ attributes added to V2 SVG serializer. #974

**Comment by z3dev** [comment]
Summary
- AMF TBD
- DXF support for 'name' attribute #684 
- OBJ TBD
- STL impossible as format does not support
- SVG support for 'id' and 'class' #974 
- 3MF

**Comment by z3dev** [comment]
Closing this issue as the relevant serializers have been changed to support names, ids, etc.
