### ISSUE TITLE
Determine segments based on radius and desired size

### ISSUE THREAD

**Issue by z3dev** [jscad/OpenJSCAD.org#568]
## Expected Behavior

It would be easy to determine the number of segments required based on the desired segment size and the radius of the shape. For example:

`let mycircle = circle({ radius: 30, segmentSize: 0.200})`

This would allow designs to have the same 'granularity', and possibly improve 3D prints.

## Actual Behavior

Not possible.

## Steps to Reproduce the Problem

  1. Not possible

## Specifications

  - Version: All
  - Platform: All
  - Environment: All

## OpenScad Calculations

Here's a port of the OpenScad calculations using FN, FS, FA.

```
/**
 * Calculate the number of fragments (segments) for the given radius.
 * @param {Number} radius - radius of the requested shape
 * @parma {Number} fn - number of fragments, if larger then zero, default 0
 * @parma {Number} fs - minimum size of a fragment, default 2, minimum value 0.01
 * @parma {Number} fa - minimum angle for a fragment, default 12, min 0.01
 *
 * @see OpenSCAD User Manual, Special Variables
 */
const getFragmentsFromRadius = (radius, fn, fs, fa) => {
  if (radius < GRID_FINE) return 3
  if (fn > 0.0) return (fn >= 3 ? Math.floor(fn) : 3)
  return Math.ceil(Math.max(Math.min(360.0 / fa, radius * 2 * Math.PI / fs), 5))
}
```

**Comment by kaosat-dev** [comment]
this is both great, and not so great @z3dev ! haha 
Sorry, brain dump :
## first aspect , design intent
There are two cases for resolution dependant designs/ shapes:
- you just want a circle for example, and it should be 'as perfect as possible' IE: no segments nor segmentSize specified : the resolution is *not* something you care for as such
- you want a specific number of segments because that is the *intent* of your design (for example a circle with 6 segments to create hex nuts for example)

## second aspect: too many possible parameters to create shapes
- I agree that your addition should be in the code because it is very practical
- BUT we already have a ton of ways of specifying how to create a circle (radius vs diameter, segments vs segmentSize etc etc)
So perhaps we could do something like having factory functions ?
ie 
- circle.createFromRadiusAndSegments() ?
- circle.createFromRadiusAndSegmentSize() ?

**Comment by z3dev** [comment]
This is available now as radiusToSegments() in utils. :)
