### ISSUE TITLE
`path2.concat()` of mirrored pair of paths followed by `extrudeRectangular` results in mesh with gaps

### ISSUE THREAD

**Issue by franknoirot** [jscad/OpenJSCAD.org#912]
## Expected Behavior
Mirroring a path and concatenating it would result in a clean, deduplicated path ready to be extruded, with the same output as creating the path without mirroring (the output of which is shown on the right in the image below).

<img width="661" alt="left: broken mesh version of chip clip model, right: resolved version" src="https://user-images.githubusercontent.com/23481541/133888774-e2967ef3-0fb2-4b35-a08b-28ed5a9826be.png">

## Actual Behavior
The resulting mesh has gaps in it when attempting to mirror a path and then concatenate the mirrored and unmirrored versions together.

## Steps to Reproduce the Problem
The source code of both versions shown in the image can be found in [this CadHub project](https://cadhub.xyz/u/franknoirot/chip-clip-jscad/ide).
  1. Create a path
  2. Concatenate the path with a mirrored version of itself
  3. Extrude the path with `extrudeRectangular()`

## Specifications
  - Version: latest
  - Platform: CadHub
  - Environment: browser

**Comment by hrgdavor** [comment]
This should be easy fix in path concat. The problem seems to be that concatenated paths share same point but resulting concated  path contains it then twice instead of merging that point into one

if I change your model to pop the problematic point it works

it is a workaround for now, but also points to the direction of the needed fix in the lib

add this to line 47 before mirroring
```js
halfOfClip.points.pop()
```
this just a workaround hack, I will look into concat code to fix this properly.

![image](https://user-images.githubusercontent.com/2480762/133909948-9fe2d7c0-7e63-4494-b922-5e9766d3a69b.png)
![image](https://user-images.githubusercontent.com/2480762/133909968-1278916e-5d29-4de7-8818-c442d2b266e5.png)

**Comment by franknoirot** [comment]
Ah thank you @hrgdavor! I suspected it was a duplicate point causing the trouble but couldn't identify the correct method to remove one of them.

Deduplicating the array of points seems like a nice ergonomic feature to include within `concat()` to me, unless you think it's too magic.

**Comment by hrgdavor** [comment]
Mentioned workaround is a hack that abuses knowledge of the path internals, so not a desirable option. 

 Adding a  check to concat is not expensive for performance, and also is very useful for end user. 

Personally, I prefer to add the fix to concat, and will post a PR soon.
